server:
  port: 8080

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 10
      maximumPoolSize: 30
      autoCommit: true

  jpa:
    generate:
      ddl: true
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update