server:
  port: 8181

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://51.158.78.210:5433/todo
    username: xuxa
    password: xuxa
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 10
      maximumPoolSize: 30
      autoCommit: true

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
